//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCode()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int CouponICoded { get; set; }
        public string Code { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Flat { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public int UsageLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CouponType CouponType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
