CREATE DATABASE AP351AteetMVCTest

USE AP351AteetMVCTest

CREATE TABLE [USER](
	ID INT PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(200) NOT NULL,
	Password NVARCHAR(100) NOT NULL
);

INSERT INTO [USER] VALUES ('ateet', 'ap123'),('bhavy', 'joshi123')

SELECT * FROM [USER]

CREATE TABLE CouponType (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL
);

INSERT INTO CouponType VALUES ('Flat'),('Percentage');

SELECT * FROM CouponType

CREATE TABLE CouponCodes (
	CouponICoded INT PRIMARY KEY IDENTITY(1,1),
	Code VARCHAR(100) NOT NULL,
	Type INT FOREIGN KEY REFERENCES CouponType(ID),
	Flat INT,
	Percentage INT,
	Expirydate DATE,
	UsageLimit INT NOT NULL,
	IsActive BIT DEFAULT 1
);

INSERT INTO CouponCodes VALUES ('PPFIRST', 1 , 50, NULL, '2023-06-07', 10, 1);
INSERT INTO CouponCodes VALUES ('PPSECOND', 2 , NULL, 10, '2023-07-06', 10, 1);

SELECT * FROM CouponCodes

CREATE TABLE ITEM(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(200) NOT NULL,
	Amount INT NOT NULL
);

INSERT INTO ITEM VALUES ('Regular Pizza', 150),('Veg Pizza', 350),('Burger', 200),('Chips', 250)

SELECT * FROM ITEM

CREATE TABLE [ORDER](
	ID INT PRIMARY KEY IDENTITY(1,1),
	OrderBy INT FOREIGN KEY REFERENCES [USER](ID),
	OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
	Total INT NOT NULL,
	PromoCode INT FOREIGN KEY REFERENCES CouponCodes(CouponICoded),
	TotalPayable INT NOT NULL,
);

INSERT INTO [ORDER] VALUES (1 ,'2023-05-27', 1000, 1, 1100);

SELECT * FROM [ORDER]

CREATE TABLE ORDERITEM(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ItemID INT FOREIGN KEY REFERENCES ITEM(ID),
	Qty INT NOT NULL,
	Total INT NOT NULL,
	OrderID INT FOREIGN KEY REFERENCES [ORDER](ID),
);

INSERT INTO ORDERITEM VALUES (1, 2, 300, 1)
INSERT INTO ORDERITEM VALUES (2, 2, 700, 1)

SELECT * FROM ORDERITEM

SELECT * FROM [ORDER]